apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-genai
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-genai
  template:
    metadata:
      labels:
        app: hello-genai
    spec:
      containers:
      - name: genai-app
        image: gcr.io/rishabh-genai-gateway-123/hello-genai:v1 # Update Project ID
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: genai-service
spec:
  type: ClusterIP
  selector:
    app: hello-genai
  ports:
  - port: 80
    targetPort: 8080
